language: python

python:
  - 3.5.0

services:
  - postgresql
  - memcached
env:
  -DJANGO=1.8.6

before_install:
  - export DJANGO_SETTINGS_MODULE=fredslist.travis-settings
  - export PYTHONPATH=$HOME/builds/rransom96/freds-list-evolved
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE peteslist;" -U postgres
  - python manage.py migrate

script:
  - python manage.py test